{
 "title": "NetApp NFS Share",
 "tags": [
  "monitoring",
  "nfs",
  "netapp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Zabbix Data Source",
    "query": "alexanderzobnin-zabbix-datasource"
   },
   {
    "name": "volume",
    "label": "Volume name",
    "query": "{prod}.{NetApp}.{Zabbix raw items}.{*}"
   }
  ]
 },
 "panels": [
  {
   "title": "Write/Read/Other operations per second on the $volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": {
      "filter": "(Write|Read|Other) operations per second on $volume"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Read/Write throughput in bytes per second on the $volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": {
      "filter": "(Read|Write) throughput in bytes per second on $volume"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Average latency for an operation in microseconds on the $volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": {
      "filter": "Average latency for an operation in microseconds on $volume"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used space on the $volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": { "filter": "Total used on $volume" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available space on the $volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": { "filter": "Logical available on $volume" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Inode used percentage on the $volume",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "repeat": "host",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": {
      "filter": "Inode used percentage on $volume"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logical used percent on the $volume",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": {
      "filter": "Logical used percent on $volume"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Physical used percentage on the $volume",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": {
      "filter": "Physical used percentage on $volume"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Size of the $volume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "prod" },
     "host": { "filter": "NetApp" },
     "item": { "filter": "Logical size on $volume" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}